config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("splitsy.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "receipts/",
        include("splitsy.receipts.urls", namespace="receipts")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

splitsy/receipts/urls.py
from django.conf.urls import url

from splitsy.receipts.api import views as api_views

from . import views

app_name = "receipts"
urlpatterns = [
    url(
        regex=r'^$',
        view=views.receipt_list,
        name='list'
    ), url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.ReceiptDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<pk>\d+)/update/$',
        view=views.ReceiptUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>\d+)/delete/$',
        view=views.ReceiptDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^api/$',
        view=api_views.ReceiptListCreateAPIView.as_view(),
        name='receipt_rest_api'
    ),
    # /receipt/api/:slug/
    url(
        regex=r'^api/(?P<uuid>[-\w]+)/$',
        view=api_views.ReceiptRetrieveUpdateDestroyAPIView.as_view(),
        name='receipt_rest_api'
    )
]

splitsy/users/urls.py
from django.urls import path

from splitsy.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

splitsy/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides selfupdating ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

splitsy/receipts/models.py
import os
import uuid

from django.urls import reverse
from django.conf import settings
from django.utils.safestring import mark_safe
from django.db import models


from splitsy.core.models import TimeStampedModel


class Receipt(TimeStampedModel):
    # slug = models.SlugField(unique=True)
    uuid = models.UUIDField(
        db_index=True,
        default=uuid.uuid4,
        editable=False,
        unique=True)
    image = models.ImageField(upload_to='images/raw')
    preprocessed_image = models.ImageField(upload_to='images/processed', null=True)
    text = models.TextField(null=True)
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='receipts', on_delete=models.CASCADE)

    @property
    def preprocessed_img_name(self):
        if self.preprocessed_image.name is None:
            if self.image.name is None:
                return None
            base, filename = os.path.split(self.image.name)
            return 'preprocessed_' + filename
        return os.path.split(self.preprocessed_image.name)[-1]

    def image_tag(self):
        return mark_safe('<img src="%s" class="img-thumbnail">' % (self.image.url))

    def preprocessed_image_tag(self):
        return mark_safe('<img src="%s" class="img-thumbnail">' % (self.preprocessed_image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse("receipts:detail", kwargs={"uuid": self.uuid})

    def __str__(self):
        return str(self.pk)

splitsy/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

splitsy/receipts/forms.py
from io import BytesIO

from PIL import Image

from django import forms
from django.core.files.base import ContentFile
from django.core.files.uploadedfile import InMemoryUploadedFile

from .models import Receipt
from .utils import unskew_text_in_img


class ReceiptCreation(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Receipt
        fields = ('image', 'x', 'y', 'width', 'height')

    def save(self, user, commit=True):
        receipt = super(ReceiptCreation, self).save(commit=False)
        receipt.uploaded_by = user

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(receipt.image)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)

        resized_image_io = BytesIO()
        resized_image.save(resized_image_io, format='JPEG')
        resized_file = ContentFile(resized_image_io.getvalue())
        receipt.preprocessed_image.save(receipt.preprocessed_img_name, InMemoryUploadedFile(
            resized_file,
            None, '',
            'image/jpeg',
            resized_image.size,
            receipt.image.file.charset
        ), save=False)
        unskew_text_in_img(receipt.preprocessed_image.path, receipt.preprocessed_image.path)
        if commit:
            receipt.save()
        return receipt

splitsy/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

splitsy/receipts/api/views.py
from rest_framework.generics import (
    ListCreateAPIView, RetrieveUpdateDestroyAPIView
)
from rest_framework.permissions import IsAuthenticated

from splitsy.receipts.models import Receipt

from .serializers import ReceiptSerializer


class ReceiptListCreateAPIView(ListCreateAPIView):
    queryset = Receipt.objects.all()
    serializer_class = ReceiptSerializer
    lookup_field = 'uuid'  # Don't use Receipt.id!


class ReceiptRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Receipt.objects.all()
    permission_classes = (IsAuthenticated, )
    serializer_class = ReceiptSerializer
    lookup_field = 'uuid'  # Don't use Receipt.id

splitsy/receipts/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Receipt
from .forms import ReceiptCreation


@login_required
def receipt_list(request):
    user = request.user
    if request.method == 'POST':
        form = ReceiptCreation(request.POST, request.FILES)
        if form.is_valid():
            form.save(user=user)
            return redirect('receipts:list')
    else:
        form = ReceiptCreation()
    receipts = Receipt.objects.filter(uploaded_by=user).order_by('-modified')
    return render(request, 'receipts/receipt_list.html', {'form': form, 'receipts': receipts})


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    fields = ['image']


class ReceiptDetailView(LoginRequiredMixin, DetailView):
    model = Receipt

    def get_success_url(self):
        return reverse('receipts:list')


class ReceiptUpdateView(LoginRequiredMixin, UpdateView):
    model = Receipt
    fields = ['image', 'text']

    def get_success_url(self):
        return reverse('receipts:detail', kwargs={'pk': self.object.pk})


class ReceiptDeleteView(LoginRequiredMixin, DeleteView):
    model = Receipt

    def get_success_url(self):
        return reverse('receipts:list')

splitsy/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

splitsy/templates/receipts/receipt_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Receipt: {{ object.uuid }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
      <h2>{{ object.uuid }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

<!-- Action buttons -->
<div class="row">

<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-5">
      {% if receipt.preprocessed_image %}
      <img src="{{ receipt.preprocessed_image.url }}" class="card-img" alt="Receipt Image">
      {% else %}
      <img src="{{ receipt.image.url }}" class="card-img" alt="Receipt Image">
      {% endif %}
    </div>
    <div class="col-md-7">
      <div class="card-body">
        <!-- <h5 class="card-title">{{ receipt.uuid }}</h5> -->
        <p class="card-text">
          {% if receipt.text %}
            {{ receipt.text }}
          {% else %}
            No text processed from image.
          {% endif %}
        </p>
        <p class="card-text"><small class="text-muted">Uploaded on {{ receipt.created }}</small></p>
          <a class="btn btn-primary" href="{% url 'receipts:update' object.pk %}" role="button">Update</a>
          <a class="btn btn-danger confirm-delete" href="{% url 'receipts:delete' object.pk %}">Delete</a>
      </div>
    </div>
  </div>
</div>
<!-- End Action buttons -->


</div>
{% endblock content %}
{% block javascript %}
{{ block.super }}
  <script>
  $(document).on('click', '.confirm-delete', function(){
    return confirm('Are you sure you want to delete this?');
  })</script>
{% endblock %}

splitsy/templates/receipts/receipt_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}splitsy - Receipts{% endblock %}

{% block css %}
  {{ block.super }}
  <link  href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
{% endblock %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/cropper.min.js' %}"></script>
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_image").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: NaN,
          minCropBoxWidth: 50,
          minCropBoxHeight: 50,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
<h1 class="page-header">Receipts</h1>
 <!-- FORM TO UPLOAD THE IMAGES -->
<form method="post" enctype="multipart/form-data" id="formUpload">
  {% csrf_token %}
  {{ form.as_p }}
</form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the receipt</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

<!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
<div class="row" style="margin-top: 20px">
  {% for receipt in receipts %}
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-5">
          <a href="{% url 'receipts:detail' pk=receipt.pk %}">
            {% if receipt.preprocessed_image %}
              <img src="{{ receipt.preprocessed_image.url }}" class="card-img" alt="Receipt Image">
            {% else %}
              <img src="{{ receipt.image.url }}" class="card-img" alt="Receipt Image">
            {% endif %}
          </a>
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title">{{ receipt.pk }}</h5>
            <p class="card-text">
              {% if receipt.text %}
                {{ receipt.text }}
              {% else %}
                No text processed from image.
              {% endif %}
            </p>
            <p class="card-text"><small class="text-muted">Uploaded on {{ receipt.created }}</small></p>
              <a class="btn btn-primary" href="{% url 'receipts:update' receipt.pk %}" role="button">Update</a>
              <a class="btn btn-danger confirm-delete" href="{% url 'receipts:delete' receipt.pk %}">Delete</a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}